<?php
/**
 * Created by PhpStorm.
 * User: HungChelsea
 * Date: 13-Jan-17
 * Time: 8:02 PM
 */

namespace frontend\widgets;


use common\models\AffiliateCompany;
use common\models\InfoPublic;
use yii\base\Widget;

class Footer extends  Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $footer = InfoPublic::findOne(['id'=>InfoPublic::ID_DEFAULT]);
        return $this->render('footer',['footer'=>$footer]);
    }
}