<?php
/**
 * Created by PhpStorm.
 * User: HungChelsea
 * Date: 13-Jan-17
 * Time: 8:02 PM
 */

namespace frontend\widgets;


use common\models\AffiliateCompany;
use common\models\InfoPublic;
use common\models\News;
use yii\base\Widget;

class RightContent extends  Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {

    }

    public static function getRightContent($id = null){
        if(empty($id)){
            $listNewsMoi = News::find()
                ->andWhere(['type' => News::TYPE_NEWS])
                ->andWhere(['status' => AffiliateCompany::STATUS_ACTIVE])
                ->orderBy(['updated_at' => SORT_DESC])
                ->limit(6)
                ->all();
        }else{
            $listNewsMoi = News::find()
                ->andWhere(['type' => News::TYPE_NEWS])
                ->andWhere(['status' => AffiliateCompany::STATUS_ACTIVE])
                ->andWhere('id <> :id_new',['id_news'=>$id])
                ->orderBy(['updated_at' => SORT_DESC])
                ->limit(6)
                ->all();
        }
        $dt =  new RightContent();
        return $dt->render('//right-menu/right-content',['listNewsMoi'=>$listNewsMoi]);
    }
}